package resinresin.wars.registry;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraftforge.fml.common.registry.GameRegistry;
import resinresin.wars.Blocks.BlockAncientBlock;
import resinresin.wars.Blocks.BlockAncientOre;
import resinresin.wars.Blocks.BlockBadBlock;
import resinresin.wars.Blocks.BlockBluePlate;
import resinresin.wars.Blocks.BlockBooster;
import resinresin.wars.Blocks.BlockBounce;
import resinresin.wars.Blocks.BlockBounceLow;
import resinresin.wars.Blocks.BlockCastleGreen;
import resinresin.wars.Blocks.BlockClassSelectorDonator;
import resinresin.wars.Blocks.BlockCorner1;
import resinresin.wars.Blocks.BlockCottage;
import resinresin.wars.Blocks.BlockDeadDirt;
import resinresin.wars.Blocks.BlockDecayOre;
import resinresin.wars.Blocks.BlockFireOre;
import resinresin.wars.Blocks.BlockGreenPlate;
import resinresin.wars.Blocks.BlockHill;
import resinresin.wars.Blocks.BlockInstantChestLv1;
import resinresin.wars.Blocks.BlockInstantChestLv2;
import resinresin.wars.Blocks.BlockInstantChestLv3;
import resinresin.wars.Blocks.BlockInstantChestLv4;
import resinresin.wars.Blocks.BlockLamp;
import resinresin.wars.Blocks.BlockNaturalOre;
import resinresin.wars.Blocks.BlockNostalHouse;
import resinresin.wars.Blocks.BlockPlayerTNT;
import resinresin.wars.Blocks.BlockPresentBox;
import resinresin.wars.Blocks.BlockRedPlate;
import resinresin.wars.Blocks.BlockRoadPiece;
import resinresin.wars.Blocks.BlockSelectorBasic;
import resinresin.wars.Blocks.BlockSelectorBuildings;
import resinresin.wars.Blocks.BlockSelectorGames;
import resinresin.wars.Blocks.BlockSelectorSpleef;
import resinresin.wars.Blocks.BlockSetSpawn;
import resinresin.wars.Blocks.BlockSinkSand;
import resinresin.wars.Blocks.BlockSpleefStone;
import resinresin.wars.Blocks.BlockSummoner;
import resinresin.wars.Blocks.BlockTeleporter;
import resinresin.wars.Blocks.BlockTeleporter2;
import resinresin.wars.Blocks.BlockTeleporter3;
import resinresin.wars.Blocks.BlockTeleporter4;
import resinresin.wars.Blocks.BlockTower;
import resinresin.wars.Blocks.BlockWallEnd;
import resinresin.wars.Blocks.BlockWallNS;
import resinresin.wars.Blocks.BlockWarChest;
import resinresin.wars.Blocks.BlockWaterOre;
import resinresin.wars.Blocks.BlockYellowPlate;
import resinresin.wars.Blocks.unseen.BlockCBlue;
import resinresin.wars.Blocks.unseen.BlockCGreen;
import resinresin.wars.Blocks.unseen.BlockCRed;
import resinresin.wars.Blocks.unseen.BlockCYellow;
import resinresin.wars.Blocks.unseen.BlockHungerGamesLv1Reset;
import resinresin.wars.Blocks.unseen.BlockHungerGamesLv1Start;
import resinresin.wars.Blocks.unseen.BlockHungerGamesLv2Reset;
import resinresin.wars.Blocks.unseen.BlockHungerGamesLv2Start;
import resinresin.wars.Blocks.unseen.BlockMazeReset;
import resinresin.wars.Blocks.unseen.BlockMazeStart;
import resinresin.wars.Blocks.unseen.BlockMinersSpleefMedium;
import resinresin.wars.Blocks.unseen.BlockMinersSpleefSmall;
import resinresin.wars.Blocks.unseen.BlockNaturalSpleefMedium;
import resinresin.wars.Blocks.unseen.BlockNaturalSpleefSmall;
import resinresin.wars.Blocks.unseen.BlockNetherSpleefMedium;
import resinresin.wars.Blocks.unseen.BlockNetherSpleefSmall;
import resinresin.wars.teleblocks.BlockHGT1;
import resinresin.wars.teleblocks.BlockHGT2;
import resinresin.wars.teleblocks.BlockHGT3;
import resinresin.wars.teleblocks.BlockHGT4;
import resinresin.wars.teleblocks.BlockHGT5;
import resinresin.wars.teleblocks.BlockHGT6;
import resinresin.wars.teleblocks.BlockHGT7;
import resinresin.wars.teleblocks.BlockHGT8;
import resinresin.wars.teleblocks.BlockHGTB1;
import resinresin.wars.teleblocks.BlockHGTB10;
import resinresin.wars.teleblocks.BlockHGTB11;
import resinresin.wars.teleblocks.BlockHGTB12;
import resinresin.wars.teleblocks.BlockHGTB13;
import resinresin.wars.teleblocks.BlockHGTB14;
import resinresin.wars.teleblocks.BlockHGTB15;
import resinresin.wars.teleblocks.BlockHGTB16;
import resinresin.wars.teleblocks.BlockHGTB17;
import resinresin.wars.teleblocks.BlockHGTB18;
import resinresin.wars.teleblocks.BlockHGTB19;
import resinresin.wars.teleblocks.BlockHGTB2;
import resinresin.wars.teleblocks.BlockHGTB20;
import resinresin.wars.teleblocks.BlockHGTB21;
import resinresin.wars.teleblocks.BlockHGTB22;
import resinresin.wars.teleblocks.BlockHGTB23;
import resinresin.wars.teleblocks.BlockHGTB24;
import resinresin.wars.teleblocks.BlockHGTB3;
import resinresin.wars.teleblocks.BlockHGTB4;
import resinresin.wars.teleblocks.BlockHGTB5;
import resinresin.wars.teleblocks.BlockHGTB6;
import resinresin.wars.teleblocks.BlockHGTB7;
import resinresin.wars.teleblocks.BlockHGTB8;
import resinresin.wars.teleblocks.BlockHGTB9;
import resinresin.wars.teleblocks.BlockHGTBM;
import resinresin.wars.teleblocks.BlockHGTM;

public class WarsBlocks {

	public static Block castleSelector;
	public static Block controlRed;
	public static Block controlGreen;
	public static Block controlBlue;
	public static Block controlYellow;
	public static Block mazeReset;
	public static Block mazeStart;
	public static Block chestPak;
	public static Block hill;
	public static Block cottage;
	public static Block gamesSelector;
	public static Block nSpleefS;
	public static Block nSpleefM;
	public static Block pSpleefS;
	public static Block pSpleefM;
	public static Block mSpleefS;
	public static Block mSpleefM;
	public static Block spleefSelector;
	public static Block ancientOre;
	public static Block deadDirt;
	public static Block ancientBlock;
	public static Block presentBox;
	public static Block spleefStone;
	public static Block sinkSand;
	public static Block fireOre;
	public static Block waterOre;
	public static Block decayOre;
	public static Block naturalOre;
	public static Block bounceBlock;
	public static Block boostBlock;
	public static Block sumBlock;
	public static Block bounceBlockLow;
	public static Block badBlock;
	public static Block buildingSelector;
	public static Block insChest1;
	public static Block insChest2;
	public static Block insChest3;
	public static Block insChest4;
	public static Block warChest;
	public static Block hgLv1start;
	public static Block hgLv1reset;
	public static Block hgLv2start;
	public static Block hgLv2reset;
	public static Block teleporterBlock4;
	public static Block teleporterBlock3;
	public static Block teleporterBlock2;
	public static Block teleporterBlock;
	public static Block hgTele1;
	public static Block hgTele2;
	public static Block hgTele3;
	public static Block hgTele4;
	public static Block hgTele5;
	public static Block hgTele6;
	public static Block hgTele7;
	public static Block hgTele8;
	public static Block hgTeleMain;
	public static Block hgTeleb1;
	public static Block hgTeleb2;
	public static Block hgTeleb3;
	public static Block hgTeleb4;
	public static Block hgTeleb5;
	public static Block hgTeleb6;
	public static Block hgTeleb7;
	public static Block hgTeleb8;
	public static Block hgTeleb9;
	public static Block hgTeleb10;
	public static Block hgTeleb11;
	public static Block hgTeleb12;
	public static Block hgTeleb13;
	public static Block hgTeleb14;
	public static Block hgTeleb15;
	public static Block hgTeleb16;
	public static Block hgTeleb17;
	public static Block hgTeleb18;
	public static Block hgTeleb19;
	public static Block hgTeleb20;
	public static Block hgTeleb21;
	public static Block hgTeleb22;
	public static Block hgTeleb23;
	public static Block hgTeleb24;
	public static Block hgTelebM;
	public static Block playerTNT;
	public static Block setSpawn;
	public static Block wallNS;
	public static Block corner1;
	public static Block lamp;
	public static Block nostalHouse;
	public static Block roadPiece;
	public static Block tower;
	public static Block wallEnd;
	public static Block greenPlate;
	public static Block redPlate;
	public static Block bluePlate;
	public static Block yellowPlate;
	public static Block warsTeleBlock;
	public static Block classSelect;
	public static Block classSelectDonator;

	public static void createBlocks() {

		deadDirt = new BlockDeadDirt().setUnlocalizedName("DeadDirt").setHardness(0.5F).setStepSound(Block.soundTypeGrass);
		controlRed = new BlockCRed().setUnlocalizedName("ControlRed").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		controlGreen = new BlockCGreen().setUnlocalizedName("ControlGreen").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		controlBlue = new BlockCBlue().setUnlocalizedName("ControlBlue").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		controlYellow = new BlockCYellow().setUnlocalizedName("ControlYellow").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		mazeReset = new BlockMazeReset().setUnlocalizedName("Reset").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		mazeStart = new BlockMazeStart().setUnlocalizedName("Start").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		nSpleefS = new BlockNetherSpleefSmall().setBlockUnbreakable().setUnlocalizedName("SpleefNetherSmall").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		nSpleefM = new BlockNetherSpleefMedium().setBlockUnbreakable().setUnlocalizedName("SpleefNetherMedium").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		pSpleefS = new BlockNaturalSpleefSmall().setBlockUnbreakable().setUnlocalizedName("SpleefNaturalSmall").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		pSpleefM = new BlockNaturalSpleefMedium().setBlockUnbreakable().setUnlocalizedName("SpleefNaturalMedium").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		mSpleefS = new BlockMinersSpleefSmall().setBlockUnbreakable().setUnlocalizedName("SpleefMinersSmall").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		mSpleefM = new BlockMinersSpleefMedium().setBlockUnbreakable().setUnlocalizedName("SpleefMinersMedium").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		hgLv1start = new BlockHungerGamesLv1Start().setUnlocalizedName("Start").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		hgLv1reset = new BlockHungerGamesLv1Reset().setUnlocalizedName("Reset").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		hgLv2start = new BlockHungerGamesLv2Start().setUnlocalizedName("Start").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		hgLv2reset = new BlockHungerGamesLv2Reset().setUnlocalizedName("Reset").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		hgTele1 = new BlockHGT1().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele2 = new BlockHGT2().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele3 = new BlockHGT3().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele4 = new BlockHGT4().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele5 = new BlockHGT5().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele6 = new BlockHGT6().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele7 = new BlockHGT7().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTele8 = new BlockHGT8().setUnlocalizedName("HgPointLv1").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleMain = new BlockHGTM().setUnlocalizedName("HgLv1Tele").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		hgTeleb1 = new BlockHGTB1().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb2 = new BlockHGTB2().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb3 = new BlockHGTB3().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb4 = new BlockHGTB4().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb5 = new BlockHGTB5().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb6 = new BlockHGTB6().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb7 = new BlockHGTB7().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb8 = new BlockHGTB8().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb9 = new BlockHGTB9().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb10 = new BlockHGTB10().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb11 = new BlockHGTB11().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb12 = new BlockHGTB12().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb13 = new BlockHGTB13().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb14 = new BlockHGTB14().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb15 = new BlockHGTB15().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb16 = new BlockHGTB16().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb17 = new BlockHGTB17().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb18 = new BlockHGTB18().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb19 = new BlockHGTB19().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb20 = new BlockHGTB20().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb21 = new BlockHGTB21().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb22 = new BlockHGTB22().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb23 = new BlockHGTB23().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTeleb24 = new BlockHGTB24().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		hgTelebM = new BlockHGTBM().setUnlocalizedName("HgPointLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		castleSelector = new BlockCastleGreen().setUnlocalizedName("CastleSelector").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		spleefSelector = new BlockSelectorSpleef().setBlockUnbreakable().setUnlocalizedName("SpleefSelector").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		buildingSelector = new BlockSelectorBuildings().setBlockUnbreakable().setUnlocalizedName("BuildingSelector").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		gamesSelector = new BlockSelectorGames().setBlockUnbreakable().setUnlocalizedName("GamesSelector").setStepSound(Block.soundTypeStone);
		classSelect = new BlockSelectorBasic().setBlockUnbreakable().setUnlocalizedName("ClassSelector").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		classSelectDonator = new BlockClassSelectorDonator().setBlockUnbreakable().setUnlocalizedName("ClassSelectorDonator").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		teleporterBlock4 = new BlockTeleporter4().setHardness(5).setResistance(10).setStepSound(Block.soundTypeStone).setUnlocalizedName("TeleLv4");
		teleporterBlock3 = new BlockTeleporter3().setHardness(5).setResistance(10).setStepSound(Block.soundTypeStone).setUnlocalizedName("TeleLv3");
		teleporterBlock2 = new BlockTeleporter2().setHardness(5).setResistance(10).setStepSound(Block.soundTypeStone).setUnlocalizedName("TeleLv2");
		teleporterBlock = new BlockTeleporter().setHardness(5).setResistance(10).setStepSound(Block.soundTypeStone).setUnlocalizedName("TeleLv1");
		hill = new BlockHill().setUnlocalizedName("Hill").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		cottage = new BlockCottage().setUnlocalizedName("Cottage").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		wallNS = new BlockWallNS(hill, 0).setBlockUnbreakable().setUnlocalizedName("Wall2").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		corner1 = new BlockCorner1().setBlockUnbreakable().setUnlocalizedName("Corner1").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		lamp = new BlockLamp().setBlockUnbreakable().setUnlocalizedName("Lamp").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		nostalHouse = new BlockNostalHouse().setBlockUnbreakable().setUnlocalizedName("FirstHouse").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		roadPiece = new BlockRoadPiece().setBlockUnbreakable().setUnlocalizedName("Road").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		tower = new BlockTower().setBlockUnbreakable().setUnlocalizedName("Tower").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		wallEnd = new BlockWallEnd().setBlockUnbreakable().setUnlocalizedName("WallEnd").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		bounceBlock = new BlockBounce().setBlockUnbreakable().setUnlocalizedName("BounceHigh").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		boostBlock = new BlockBooster().setBlockUnbreakable().setUnlocalizedName("Booster").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		sumBlock = new BlockSummoner().setUnlocalizedName("Summoner").setHardness(0.5F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		bounceBlockLow = new BlockBounceLow().setBlockUnbreakable().setUnlocalizedName("BounceLow").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		badBlock = new BlockBadBlock().setUnlocalizedName("DoomBlock").setBlockUnbreakable().setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		ancientOre = new BlockAncientOre().setHardness(3F).setUnlocalizedName("AncientOre").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		ancientBlock = new BlockAncientBlock().setHardness(5F).setUnlocalizedName("AncientBlock").setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		presentBox = new BlockPresentBox().setHardness(5F).setUnlocalizedName("PresentBox").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		spleefStone = new BlockSpleefStone().setHardness(5F).setUnlocalizedName("SpleefStone").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		sinkSand = new BlockSinkSand().setUnlocalizedName("SinkSand").setBlockUnbreakable().setHardness(6.9F).setStepSound(Block.soundTypeStone);
		fireOre = new BlockFireOre().setHardness(3F).setUnlocalizedName("FireOre").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		waterOre = new BlockWaterOre().setHardness(3F).setUnlocalizedName("WaterOre").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		decayOre = new BlockDecayOre().setHardness(3F).setUnlocalizedName("DecayOre").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		naturalOre = new BlockNaturalOre().setHardness(3F).setUnlocalizedName("OreNatural").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		insChest1 = new BlockInstantChestLv1().setBlockUnbreakable().setUnlocalizedName("HgBoxLv1").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		insChest2 = new BlockInstantChestLv2().setUnlocalizedName("HgBoxLv2").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		insChest3 = new BlockInstantChestLv3().setBlockUnbreakable().setUnlocalizedName("HgBoxLv3").setResistance(6000000F).setStepSound(Block.soundTypeStone);
		insChest4 = new BlockInstantChestLv4().setUnlocalizedName("HgBoxLv4").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		warChest = new BlockWarChest().setBlockUnbreakable().setBlockUnbreakable().setUnlocalizedName("WarChest").setResistance(6000000F).setLightLevel(0.9F).setStepSound(Block.soundTypeStone);
		playerTNT = new BlockPlayerTNT().setHardness(0.2F).setUnlocalizedName("PTNTFront").setResistance(1F).setStepSound(Block.soundTypeStone);
		setSpawn = new BlockSetSpawn().setUnlocalizedName("SpawnSetter").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone);
		redPlate = new BlockRedPlate("wool_colored_red", Material.rock, EnumMobType.mobs).setUnlocalizedName("RedPlate").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		bluePlate = new BlockBluePlate("wool_colored_blue", Material.rock, EnumMobType.mobs).setUnlocalizedName("BluePlate").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		greenPlate = new BlockGreenPlate("wool_colored_green", Material.rock, EnumMobType.mobs).setUnlocalizedName("GreenPlate").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);
		yellowPlate = new BlockYellowPlate("wool_colored_yellow", Material.rock, EnumMobType.mobs).setUnlocalizedName("YellowPlate").setBlockUnbreakable().setResistance(6000000F).setStepSound(Block.soundTypeStone).setLightLevel(0.9F);

		//		/*LanguageRegistry.addName(buildingSelector, "Selector - Buildings");
		//		LanguageRegistry.addName(spleefSelector, "Selector - Spleef");
		//		LanguageRegistry.addName(castleSelector, "Selector - Setup");
		//		LanguageRegistry.addName(controlRed, "Control Of Fire");
		//		LanguageRegistry.addName(controlGreen, "Control Of Life");
		//		LanguageRegistry.addName(controlBlue, "Control Of Water");
		//		LanguageRegistry.addName(controlYellow, "Control Of Decay");
		//		LanguageRegistry.addName(ancientOre, "Ancient Ore");
		//		LanguageRegistry.addName(boostBlock, "Booster");
		//		LanguageRegistry.addName(bounceBlock, "Bouncer -high-");
		//		LanguageRegistry.addName(sumBlock, "Summoner");
		//		LanguageRegistry.addName(insChest1, "Hunger Games Chest -LV1-");
		//		LanguageRegistry.addName(insChest3, "Hunger Games Chest -LV3-");
		//		LanguageRegistry.addName(warChest, "War Chest");
		//		LanguageRegistry.addName(gamesSelector, "Selector - MiniGames");
		//		LanguageRegistry.addName(hill, "A Small Aesthestic Hill");
		//		LanguageRegistry.addName(hgLv1start, "Do Not Use This!");
		//		LanguageRegistry.addName(insChest2, "Hunger Games Chest -Lv2-");
		//		LanguageRegistry.addName(insChest4, "Hunger Games Chest -Lv4-");
		//		LanguageRegistry.addName(bounceBlockLow, "Bouncer -low-");
		//		LanguageRegistry.addName(deadDirt, "Dead Dirt");
		//		LanguageRegistry.addName(cottage, "Community Creation : Pylickuz's Cottage");
		//		LanguageRegistry.addName(teleporterBlock, "\u00a79Teleporter MK1");
		//		LanguageRegistry.addName(teleporterBlock2, "\u00a75Teleporter MK2");
		//		LanguageRegistry.addName(teleporterBlock3, "\u00a76Teleporter MK3");
		//		LanguageRegistry.addName(teleporterBlock4, "\u00a73Teleporter MK4");
		//		LanguageRegistry.addName(ancientBlock, "\u00a73Ancient Block");
		//		LanguageRegistry.addName(presentBox, "Present Box");
		//		LanguageRegistry.addName(spleefStone, "Spleef Stone");
		//		LanguageRegistry.addName(badBlock, "Doom Block");
		//		LanguageRegistry.addName(sinkSand, "Sink Sand");
		//		LanguageRegistry.addName(fireOre, "Firernite Ore");
		//		LanguageRegistry.addName(waterOre, "Waternate Ore");
		//		LanguageRegistry.addName(decayOre, "Decayenate Ore");
		//		LanguageRegistry.addName(naturalOre, "Natralite Ore");
		//		LanguageRegistry.addName(playerTNT, "Tech Player TNT");
		//		LanguageRegistry.addName(setSpawn, "World Spawn Setter");
		//		LanguageRegistry.addName(classSelect, "Class Selector");
		//		LanguageRegistry.addName(classSelectDonator, "Donator Class Selector");
		//		LanguageRegistry.addName(wallNS, "Wall Piece Side");
		//		LanguageRegistry.addName(corner1, "Wall Piece Corner");
		//		LanguageRegistry.addName(lamp, "Small Lamp");
		//		LanguageRegistry.addName(nostalHouse, "Easter Egg : My very first minecraft house (Made in 1.7.3 :D)");
		//		LanguageRegistry.addName(roadPiece, "Road Creator");
		//		LanguageRegistry.addName(tower, "Tower");
		//		LanguageRegistry.addName(wallEnd, "Wall Piece End");
		//		LanguageRegistry.addName(redPlate, "Red Team Pressure Plate");
		//		LanguageRegistry.addName(bluePlate, "Blue Team Pressure Plate");
		//		LanguageRegistry.addName(yellowPlate, "Yellow Team Pressure Plate");
		//		LanguageRegistry.addName(greenPlate, "Green Team Pressure Plate");*/

		GameRegistry.registerBlock(buildingSelector, "buildingSelector");
		GameRegistry.registerBlock(spleefSelector, "spleefSelector");
		GameRegistry.registerBlock(castleSelector, "castleSelector");
		GameRegistry.registerBlock(controlRed, "controlRed");
		GameRegistry.registerBlock(controlGreen, "controlGreen");
		GameRegistry.registerBlock(controlBlue, "controlBlue");
		GameRegistry.registerBlock(controlYellow, "controlYellow");
		GameRegistry.registerBlock(ancientOre, "ancientOre");
		GameRegistry.registerBlock(boostBlock, "boostBlock");
		GameRegistry.registerBlock(bounceBlock, "bounceBlock");
		GameRegistry.registerBlock(sumBlock, "sumBlock");
		GameRegistry.registerBlock(insChest1, "insChest1");
		GameRegistry.registerBlock(insChest3, "insChest3");
		GameRegistry.registerBlock(warChest, "warChest");
		GameRegistry.registerBlock(gamesSelector, "gamesSelector");
		GameRegistry.registerBlock(hill, "hill");
		GameRegistry.registerBlock(hgLv1start, "hgLv1start");
		GameRegistry.registerBlock(insChest2, "inschest2");
		GameRegistry.registerBlock(insChest4, "insChest4");
		GameRegistry.registerBlock(bounceBlockLow, "bounceBlockLow");
		GameRegistry.registerBlock(deadDirt, "deadDirt");
		GameRegistry.registerBlock(cottage, "cottage");
		GameRegistry.registerBlock(teleporterBlock, "teleporterBlock");
		GameRegistry.registerBlock(teleporterBlock2, "teleporterBlock2");
		GameRegistry.registerBlock(teleporterBlock3, "teleporterBlock3");
		GameRegistry.registerBlock(teleporterBlock4, "teleporterBlock4");
		GameRegistry.registerBlock(ancientBlock, "ancientBlock");
		GameRegistry.registerBlock(presentBox, "presentBox");
		GameRegistry.registerBlock(spleefStone, "spleefStone");
		GameRegistry.registerBlock(badBlock, "badBlock");
		GameRegistry.registerBlock(sinkSand, "sinkSand");
		GameRegistry.registerBlock(fireOre, "fireOre");
		GameRegistry.registerBlock(waterOre, "waterOre");
		GameRegistry.registerBlock(decayOre, "decayOre");
		GameRegistry.registerBlock(naturalOre, "naturalOre");
		GameRegistry.registerBlock(setSpawn, "setSpawn");
		GameRegistry.registerBlock(classSelect, "classSelect");
		GameRegistry.registerBlock(classSelectDonator, "classSelectDonator");
		GameRegistry.registerBlock(wallNS, "wallNS");
		GameRegistry.registerBlock(corner1, "corner1");
		GameRegistry.registerBlock(lamp, "lamp");
		GameRegistry.registerBlock(nostalHouse, "nostalHouse");
		GameRegistry.registerBlock(roadPiece, "roadPiece");
		GameRegistry.registerBlock(tower, "tower");
		GameRegistry.registerBlock(wallEnd, "wallEnd");
		GameRegistry.registerBlock(redPlate, "redPlate");
		GameRegistry.registerBlock(bluePlate, "bluePlate");
		GameRegistry.registerBlock(yellowPlate, "yellowPlate");
		GameRegistry.registerBlock(greenPlate, "greenPlate");
		GameRegistry.registerBlock(playerTNT, "ItemPTNTBlock.class");
	}

}